version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: pg
    #tty: true
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    network_mode: 'host'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    expose:
      - 5432
volumes:
  data:
    external: true
